---
- name: Install
  yum:
    name: nginx
    state: present

- name: Set configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  #    validate: nginx -t -c %s
  with_items:
    - {'src': 'nginx.conf.j2', 'dest': '/etc/nginx/nginx.conf'}
    - {'src': 'default.conf.j2', 'dest': '/etc/nginx/conf.d/default.conf'}
  notify:
    - reload_nginx

- name: Start
  systemd:
    name: nginx
    enabled: yes
    state: started
    daemon_reload: yes
