---
- name: Add YUM repo
  template:
    src: mongodb-org-4.4.repo
    dest: /etc/yum.repos.d/mongodb-org-4.4.repo
    owner: root
    group: root
    mode: 0644

- name: Install
  yum:
    name: mongodb-org
    state: present

- name: Copy mongos.conf
  template:
    src: mongos.conf
    dest: /etc/mongos.conf

- name: Add unit file
  template:
    src: mongos.service
    dest: /usr/lib/systemd/system/mongos.service
    owner: root
    group: root
    mode: 0644

- name: Disable mongod
  systemd:
    name: mongod
    enabled: no
    state: stopped

- name: Start mongos
  systemd:
    name: mongos
    enabled: yes
    state: started
    daemon_reload: yes

- name: Open firewall port
  ansible.posix.firewalld:
    port: 27017/tcp
    permanent: yes
    state: enabled
    immediate: yes
