---
- name: Add YUM repo
  copy:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo
    owner: root
    group: root
    mode: 0644

- name: Install
  yum:
    name: grafana
    state: present

- name: Start
  systemd:
    name: grafana-server
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Open firewall port
  firewalld:
    port: 3000/tcp
    permanent: yes
    state: enabled
    immediate: yes
