---
- name: Prometheus
  hosts: prometheus-servers
  become: true
  roles:
    - role: node_exporter
    - role: prometheus_pushgateway
    - role: prometheus_alertmanager
    - role: prometheus
    - role: grafana
