---
- name: Add YUM repo
  copy:
    src: mongodb-org-4.4.repo
    dest: /etc/yum.repos.d/mongodb-org-4.4.repo
    owner: root
    group: root
    mode: 0644

- name: Install
  yum:
    name: mongodb-org
    state: present

- name: Copy mongod.conf
  template:
    src: mongod.conf
    dest: /etc/mongod.conf

- name: Start
  systemd:
    name: mongod
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Open firewall port
  firewalld:
    port: 27017/tcp
    permanent: yes
    state: enabled
    immediate: yes
