---
- name: Add YUM repo
  copy:
    src: kibana.repo
    dest: /etc/yum.repos.d/kibana.repo
    owner: root
    group: root
    mode: 0644

- name: Install
  yum:
    name: kibana
    state: present

- name: Copy kibana.yml
  copy:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml

- name: Start
  systemd:
    name: kibana
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Open firewall port
  firewalld:
    port: 5601/tcp
    permanent: yes
    state: enabled
    immediate: yes
