---
- name: Unarchive
  unarchive:
    src: https://github.com/prometheus/pushgateway/releases/download/v{{ pushgateway_version }}/pushgateway-{{ pushgateway_version }}.linux-amd64.tar.gz
    dest: /usr/local/src/
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: 0755
    remote_src: true
    creates: /usr/local/src/pushgateway-{{ pushgateway_version }}.linux-amd64/

- name: Create symbolic link
  file:
    src: /usr/local/src/pushgateway-{{ pushgateway_version }}.linux-amd64/pushgateway
    dest: /usr/local/pushgateway
    state: link

- name: Add unit file
  template:
    src: pushgateway.service
    dest: /usr/lib/systemd/system/pushgateway.service
    owner: root
    group: root
    mode: 0644

- name: Start
  systemd:
    name: pushgateway
    enabled: yes
    state: started
    daemon_reload: yes

- name: Open firewall port
  ansible.posix.firewalld:
    port: 9091/tcp
    permanent: yes
    state: enabled
    immediate: yes
