---
- name: Unarchive
  unarchive:
    src: https://www.apache.org/dist/kafka/{{ kafka_version }}/kafka_2.13-{{ kafka_version }}.tgz
    dest: /usr/local/src/
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: 0755
    remote_src: true
    creates: /usr/local/src/kafka_2.13-{{ kafka_version }}

- name: Create symbolic link
  file:
    src: /usr/local/src/kafka_2.13-{{ kafka_version }}
    dest: /usr/local/kafka
    state: link

- name: Add unit file
  copy:
    src: kafka-connect.service
    dest: /usr/lib/systemd/system/kafka-connect.service
    owner: root
    group: root
    mode: 0644

- name: Copy config files
  template:
    src: "{{item}}"
    dest: /usr/local/kafka/config/
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: 0755
  loop:
    - connect-distributed.properties

- name: Start Kafka Connect
  systemd:
    name: kafka-connect
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Open firewall port
  firewalld:
    port: 8083/tcp
    permanent: yes
    state: enabled
    immediate: yes
