---
- name: Unarchive
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /usr/local/src/
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: 0755
    remote_src: true
    creates: /usr/local/src/node_exporter-{{ node_exporter_version }}.linux-amd64/

- name: Create symbolic link
  file:
    src: /usr/local/src/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    dest: /usr/local/node_exporter
    state: link

- name: Add unit file
  template:
    src: node_exporter.service
    dest: /usr/lib/systemd/system/node_exporter.service
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: 0644

- name: Start
  systemd:
    name: node_exporter
    enabled: yes
    state: started
    daemon_reload: yes

- name: Open firewall port
  ansible.posix.firewalld:
    port: 9100/tcp
    permanent: yes
    state: enabled
    immediate: yes
