---
- name: Add YUM repo
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: root
    group: root
    mode: 0644

- name: Install
  yum:
    name: elasticsearch
    state: present

- name: Copy elasticsearch.yml
  copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml

- name: Start
  systemd:
    name: elasticsearch
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Open firewall port
  firewalld:
    port: 9200/tcp
    permanent: yes
    state: enabled
    immediate: yes
