---
- name: Unarchive
  unarchive:
    src: https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysqld_exporter_version }}/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64.tar.gz
    dest: /usr/local/src/
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: 0755
    remote_src: true
    creates: /usr/local/src/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64/

- name: Create symbolic link
  file:
    src: /usr/local/src/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64/mysqld_exporter
    dest: /usr/local/mysqld_exporter
    state: link

- name: Add unit file
  template:
    src: mysqld_exporter.service
    dest: /usr/lib/systemd/system/mysqld_exporter.service
    owner: root
    group: root
    mode: 0644

- name: Start
  systemd:
    name: mysqld_exporter
    enabled: yes
    state: started
    daemon_reload: yes

- name: Open firewall port
  ansible.posix.firewalld:
    port: 9104/tcp
    permanent: yes
    state: enabled
    immediate: yes
