---
- name: Unarchive
  unarchive:
    src: https://www.apache.org/dist/kafka/{{ kafka_version }}/kafka_2.13-{{ kafka_version }}.tgz
    dest: /usr/local/src/
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: 0755
    remote_src: true
    creates: /usr/local/src/kafka_2.13-{{ kafka_version }}

- name: Create symbolic link
  file:
    src: /usr/local/src/kafka_2.13-{{ kafka_version }}
    dest: /usr/local/kafka
    state: link

- name: Add unit file
  copy:
    src: kafka-zookeeper.service
    dest: /usr/lib/systemd/system/kafka-zookeeper.service
    owner: root
    group: root
    mode: 0644

- name: Start ZooKeeper
  systemd:
    name: kafka-zookeeper
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Open firewall ports
  firewalld:
    port: "{{ item.port }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - { 'port': 2181 }
    - { 'port': 2888 }
    - { 'port': 3888 }
