---
- name: Elasticsearch
  hosts: elasticsearch
  become: true
  roles:
    - role: elasticsearch
    - role: elasticsearch_plugin
  tags:
    - elasticsearch

- name: Kibana
  hosts: kibana
  become: true
  roles:
    - role: kibana
  tags:
    - kibana
