---
- name: Kafka Zookeeper
  hosts: kafka_zookeeper
  become: true
  roles:
    - role: node_exporter
    - role: openjdk
    - role: kafka_zookeeper
  tags:
    - zookeeper

- name: Kafka Brokers
  hosts: kafka
  become: true
  vars:
    zookeeper_connect: 192.168.13.229:2181
  roles:
    - role: node_exporter
    - role: openjdk
    - role: kafka
  tags:
    - kafka

- name: Kafka Connect
  hosts: kafka_connect
  become: true
  vars:
    bootstrap_servers: 192.168.13.226:9092
  roles:
    - role: node_exporter
    - role: openjdk
    - role: kafka_connect
  tags:
    - connect
