---
- name: Add YUM repo
  copy:
    src: mysql-community.repo
    dest: /etc/yum.repos.d/mysql-community.repo
    owner: root
    group: root
    mode: 0644

- name: Install
  yum:
    name: mysql-server
    state: present

- name: Copy my.cnf
  copy:
    src: my.cnf
    dest: /etc/my.cnf

- name: Start
  systemd:
    name: mysqld
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Open firewall port
  firewalld:
    port: 3306/tcp
    permanent: yes
    state: enabled
    immediate: yes
